
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";



import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Leaderboard = lazy(() => import("./pages/Leaderboard.tsx"));
const ModelComparison = lazy(() => import("./pages/ModelComparison.tsx"));
const RewardFunctionStudio = lazy(() => import("./pages/RewardFunctionStudio.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));
const TrackAnalysis = lazy(() => import("./pages/TrackAnalysis.tsx"));
const TrainingHistory = lazy(() => import("./pages/TrainingHistory.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/leaderboard", element: <Leaderboard />},
	{ path: "/model-comparison", element: <ModelComparison />},
	{ path: "/modelcomparison", element: <ModelComparison />},
	{ path: "/reward-function-studio", element: <RewardFunctionStudio />},
	{ path: "/rewardfunctionstudio", element: <RewardFunctionStudio />},
	{ path: "/settings", element: <Settings />},
	{ path: "/track-analysis", element: <TrackAnalysis />},
	{ path: "/trackanalysis", element: <TrackAnalysis />},
	{ path: "/training-history", element: <TrainingHistory />},
	{ path: "/traininghistory", element: <TrainingHistory />},

];
